POST http://localhost:5000/api/customer/create
Content-Type: application/json

{
    "CUS_ID":"986469767",
    "CUS_NAME":"Nguyễn Văn Chiến 4",
    "CUS_PHONE":"0328009123"
}
################################
GET http://localhost:5000/api/customer
################################
DELETE http://localhost:5000/api/customer/986469767
################################
PUT http://localhost:5000/api/customer/131313da 
Content-Type: application/json

{
    "CUS_ID":"131313da",
    "CUS_NAME":"ok21",
    "CUS_PHONE":"22313"
}
################################
POST http://localhost:5000/api/plane/create
Content-Type: application/json

{
    "PLANE_CODE": "may6", 
    "CHAIR_FREE": "A01 A02 A03 A04 A05 A06 A07 A08 A09 A10 A11 A12 A13 A14 A15 A16 B17 B18 B19 B20 B21 B22 B23 B24 B25 B26 B27 B28 B29 B30 B31 B32 B33 B34 B35 B36 B37 B38 B39 B40 C41 C42 C43 C44 C45 C46 C47 C48 C49 C50 C51 C52 C53 C54 C55 C56 C57 C58 C59 C60 C61 C62 C63 C64 C65 C66 C67 C68 C69 C70 C71 C72 C73 C74 C75 C76",
    "CHAIR_BOOKED":""
}
################################################################
PUT http://localhost:5000/api/plane/may2
Content-Type: application/json

{
    "PLANE_CODE": "may2", 
    "CHAIR_FREE": "A01 A02 A03 A04 A05 A06 A07 A08 A09 A10 A14 A15 A16 B17 B18 B21 B22 B23 B24 B25 B26 B27 B28 B29 B30 B31 B32 B33 B34 B35 B36 B37 B38 B39 B40 C41 C42 C43 C44 C45 C46 C47 C48 C49 C50 C51 C52 C53 C54 C55 C56 C57 C58 C59 C60 C61 C62 C63 C64 C65 C66 C67 C68 C69 C70 C71 C72 C73 C74",
    "CHAIR_BOOKED":"C75 C76 A11 A12 A13 B20 B19"
}
# A01 A02 A03 A04 A05 A06 A07 A08 A09 A10 A11 A12 A13 A14 A15 A16 B17 B18 B19 B20 B21 B22 B23 B24 B25 B26 B27 B28 B29 B30 B31 B32 B33 B34 B35 B36 B37 B38 B39 B40 C41 C42 C43 C44 C45 C46 C47 C48 C49 C50 C51 C52 C53 C54 C55 C56 C57 C58 C59 C60 C61 C62 C63 C64 C65 C66 C67 C68 C69 C70 C71 C72 C73 C74 C75 C76
################################
GET http://localhost:5000/api/plane
################################
POST http://localhost:5000/api/flight/create
Content-Type: application/json

{
    "FLI_CODE": "BĐtoHN03", 
    "PLANE_CODE": "may4",
    "FLI_S_PLACE": "Bình Định", 
    "FLI_E_PLACE": "Hà Nội", 
    "FLI_S_DATE": "12/12/2022.16:30", 
    "FLI_E_DATE": "12/12/2022.18:50"
}
################################
GET http://localhost:5000/api/flight




